// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAD.Backend.Data;

#nullable disable

namespace PAD.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116214318_agregando cuil")]
    partial class agregandocuil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("marcas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Chevrolet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Volkswagen"
                        });
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("modelos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Hilux"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Focus"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Onix"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Gol"
                        });
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Patente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ejemplar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<string>("NumeroPatente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TitularId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPatente")
                        .IsUnique();

                    b.HasIndex("TitularId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("patentes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ejemplar = "A",
                            FechaEmision = new DateOnly(2018, 6, 1),
                            NumeroPatente = "AB123CD",
                            TitularId = 1,
                            VehiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ejemplar = "B",
                            FechaEmision = new DateOnly(2019, 9, 1),
                            NumeroPatente = "AC987XY",
                            TitularId = 2,
                            VehiculoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Ejemplar = "A",
                            FechaEmision = new DateOnly(2020, 4, 10),
                            NumeroPatente = "AE555GH",
                            TitularId = 3,
                            VehiculoId = 3
                        });
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Titular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cuil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("titulares", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Dni = "30123456",
                            Email = "juan.perez@email.com",
                            Nombre = "Juan",
                            Telefono = "1123456789"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Dni = "28999888",
                            Email = "maria.gomez@email.com",
                            Nombre = "María",
                            Telefono = "1133344455"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Ramírez",
                            Dni = "27111222",
                            Email = "carlos.ramirez@email.com",
                            Nombre = "Carlos",
                            Telefono = "1145566778"
                        });
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("PatenteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TitularDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("TitularOrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatenteId");

                    b.HasIndex("TitularDestinoId");

                    b.HasIndex("TitularOrigenId");

                    b.ToTable("transacciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 12500m,
                            Fecha = new DateOnly(2023, 8, 21),
                            PatenteId = 2,
                            TipoTransaccion = "TRANSFERENCIA",
                            TitularDestinoId = 2,
                            TitularOrigenId = 1
                        },
                        new
                        {
                            Id = 2,
                            Costo = 11000m,
                            Fecha = new DateOnly(2024, 9, 23),
                            PatenteId = 3,
                            TipoTransaccion = "TRANSFERENCIA",
                            TitularDestinoId = 3,
                            TitularOrigenId = 2
                        });
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaFabricacion")
                        .HasColumnType("date");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroChasis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroMotor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("NumeroChasis")
                        .IsUnique();

                    b.HasIndex("NumeroMotor")
                        .IsUnique();

                    b.ToTable("vehiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "B",
                            FechaFabricacion = new DateOnly(2018, 5, 10),
                            MarcaId = 1,
                            ModeloId = 1,
                            NumeroChasis = "CHS-TOY-001",
                            NumeroMotor = "MOT-TOY-001",
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "B",
                            FechaFabricacion = new DateOnly(2019, 8, 15),
                            MarcaId = 2,
                            ModeloId = 3,
                            NumeroChasis = "CHS-FRD-002",
                            NumeroMotor = "MOT-FRD-002",
                            Precio = 13000m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "B",
                            FechaFabricacion = new DateOnly(2020, 3, 20),
                            MarcaId = 3,
                            ModeloId = 4,
                            NumeroChasis = "CHS-CHV-003",
                            NumeroMotor = "MOT-CHV-003",
                            Precio = 11000m
                        });
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Patente", b =>
                {
                    b.HasOne("PAD.Backend.Models.Entidades.Titular", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAD.Backend.Models.Entidades.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Titular");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Transaccion", b =>
                {
                    b.HasOne("PAD.Backend.Models.Entidades.Patente", "Patente")
                        .WithMany()
                        .HasForeignKey("PatenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAD.Backend.Models.Entidades.Titular", "TitularDestino")
                        .WithMany()
                        .HasForeignKey("TitularDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAD.Backend.Models.Entidades.Titular", "TitularOrigen")
                        .WithMany()
                        .HasForeignKey("TitularOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patente");

                    b.Navigation("TitularDestino");

                    b.Navigation("TitularOrigen");
                });

            modelBuilder.Entity("PAD.Backend.Models.Entidades.Vehiculo", b =>
                {
                    b.HasOne("PAD.Backend.Models.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAD.Backend.Models.Entidades.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Modelo");
                });
#pragma warning restore 612, 618
        }
    }
}
